### ISSUE TITLE
Evaluation cause KeyError: 'gconv1.lin.weight'

### ISSUE THREAD

**Issue by wtnan2003** [MiniEval/pytorch-gken#1]
`(py3.7) nd@nd46:~/pytorch-gken$ python eval.py Keyframe.bvh 10`

Error message:
`
Processing BVH file...done!
Loading GKEN model...Traceback (most recent call last):
  File "eval.py", line 41, in <module>
    agent.load_models()
  File "/home/nd/pytorch-gken/agent.py", line 167, in load_models
    self.policy_net.load_state_dict(checkpoint['policy_model_state_dict'])
  File "/home/nd/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1392, in load_state_dict
    load(self)
  File "/home/nd/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1390, in load
    load(child, prefix + name + '.')
  File "/home/nd/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1390, in load
    load(child, prefix + name + '.')
  File "/home/nd/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1387, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/home/nd/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1310, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/home/nd/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch_geometric/nn/dense/linear.py", line 131, in _lazy_load_hook
    weight = state_dict[prefix + 'weight']
KeyError: 'gconv1.lin.weight'
`

any help would be appreciated

**Comment by MiniEval** [comment]
Please make sure you're using PyTorch Geometric 1.7.2. >2.0 versions seem to have broken compatibility with pre-trained models.

2.0+: https://pytorch-geometric.readthedocs.io/en/2.0.0/_modules/torch_geometric/nn/conv/gcn_conv.html - ```self.lin```
![image](https://user-images.githubusercontent.com/85723511/157207243-ef75be17-077c-45bf-a0cd-838ada520563.png)

1.7.2: https://pytorch-geometric.readthedocs.io/en/1.7.2/_modules/torch_geometric/nn/conv/gcn_conv.html - ```self.weight```
![image](https://user-images.githubusercontent.com/85723511/157207268-2cea2716-c055-4551-9dc9-f5551911694f.png)

**Comment by wtnan2003** [comment]
@MiniEval thanks for the quick response! problem solved thanks
